### ISSUE TITLE
rst_inc.py does not execute because it's missing sh-bang

### ISSUE THREAD

**Issue by six8** [bitranox/rst_include#1]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**

bug.

* **What is the current behavior?**

The docs say to use the command `rst_include.py`, but the actual command/script is `rst_inc.py`. When using `rst_inc.py`, it is not recognized as a Python script:

```
$ rst_inc.py
/usr/local/opt/pyenv/versions/2.7.14/bin/rst_inc.py: line 1: import: command not found
/usr/local/opt/pyenv/versions/2.7.14/bin/rst_inc.py: line 2: import: command not found
/usr/local/opt/pyenv/versions/2.7.14/bin/rst_inc.py: line 4: syntax error near unexpected token `('
/usr/local/opt/pyenv/versions/2.7.14/bin/rst_inc.py: line 4: `if sys.version_info < (3, 5):'
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

- `pip install rst_include`
- Try to execute `rst_include.py` --  get "command not found"
- Try to execute `rst_inc.py` --  get "import: command not found" because it's trying to execute it as bash.

* **What is the expected behavior?**

- Doc says `rst_inc.py`
- Running `rst_inc.py` on command line executes as a Python script.

* **What is the motivation / use case for changing the behavior?**

So the command can be used.

* **Please tell us about your environment:**

- Release Number of the Repository used : 1.04
- Python Version :  2.7.14
- OS, OS Version :  MacOS 10.14.4

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

The fix is to add `#!/usr/bin/env python` to the top of `rst_inc.py`

**Comment by bitranox** [comment]
Dear six8 - thanks for the feedback.
besides the documentation glitches, please note that rst_include will NOT work on python  2.7.x - 
if You really need that, You are welcome to fork it and make a backport - it should not be too hard .... 

I updated the documentation - for the shebang I will look into it. 
setup.py should install  "rst_inc.py" as a console script - see "setup.py" : 

```
setup(
    name='rst_include',
    version='1.0.4',
    description=description,
    long_description=long_description,
    long_description_content_type='text/x-rst',
    author='Robert Nowotny',
    author_email='rnowotny1966@gmail.com',
    url='https://github.com/bitranox/rst_include',
    packages=['rst_include', 'rst_include.libs'],
    install_requires=['pytest',
                      'typing'],
    classifiers=CLASSIFIERS,
    setup_requires=['pytest-runner'],
    tests_require=['pytest'],
    scripts=['rst_inc.py'])
```
but I will change that to the newer, preferred method, but I need to refractor the main() a bit : 

```
setup(
    ...
    entry_points = {
        'console_scripts': ['rst_inc=rst_inc:main'],
    }
    ...
)
```
and test on linux / osX.
It slipped through, since I myself only use the "build_docs.py" build script under pycharm / travis ;-)
when testing on Windows, the "scripts=['rst_inc.py']" worked perfectly ... 
however, if the shebang is still needed, I will add it ... let me test first the entry_point method ... 

I will keep You updated

**Comment by bitranox** [comment]
Hey, I drafted a new release V1.0.5 - rst_include is now registered correctly as console command: 

```
# install it : 
$> pip install rst_include --upgrade

# either issue on commandline: 
$> rst_include -h 

# or via python interpreter : 
$> python -m rst_include -h 

```

in case of any questions or issues let me know !
Robert

**Comment by bitranox** [comment]
Does it work for You ?

**Comment by six8** [comment]
I noticed it didn't work in 2.7, but since it was just for documentation I was able to run it with Python 3. The `rst_include` command works now in 1.0.5. Thanks!

**Comment by bitranox** [comment]
great ! 
please note that it is now also possible to include jupyter notebooks
